name: stock_scan_parser
description: Mobile replica for Stock Scan Parser assignment (Clean Architecture)
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.1.0

  # State management & DI
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3
  get_it: ^8.1.1
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
